---
# This document was created based on the format used in mclust.rmd 
# Scrucca L., Fop M., Murphy T. B. and Raftery A. E. (2016) mclust 5:
#   clustering, classification and density estimation using Gaussian finite
#   mixture models The R Journal 8/1, pp. 205-233
# https://cran.r-project.org/web/packages/mclust/vignettes/mclust.html
--- 


---
title: "A quick tour of mixMVPLN"
author: "Anjali Silva"
date: "`r format(Sys.time(), '%d %b %Y')`"
output: 
  rmarkdown::html_vignette:
    toc: true
    number_sections: false
vignette: >
  %\VignetteIndexEntry{A quick tour of mixMVPLN}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(fig.align = "center", 
               out.width = "90%",
               fig.width = 6, fig.height = 5.5,
               dev.args=list(pointsize=10),
               par = TRUE, # needed for setting hook 
               collapse = TRUE, # collapse input & ouput code in chunks
               warning = FALSE)

knit_hooks$set(par = function(before, options, envir)
  { if(before && options$fig.show != "none") 
       par(family = "sans", mar=c(4.1,4.1,1.1,1.1), mgp=c(3,1,0), tcl=-0.5)
})
set.seed(1) # for exact reproducibility
```


## Introduction

**mixMVPLN** is an R package for model-based clustering based on mixtures of matrix variate Poisson-log normal (MVPLN) distributions. It is applicable for clustering of three-way count data. **mixMVPLN** provides functions for parameter estimation via the Markov chain Monte Carlo expectation-maximization (MCMC-EM) algorithm. Information criteria (AIC, BIC, AIC3 and ICL) are offered for model selection. Also included is a function for simulating data from this model. Function *mvplnClustering* within **mixMVPLN** makes use of the **parallel** R package to run each component/cluster (G) in parallel, as each G is independent from another. 

This document gives a quick tour of **mixMVPLN** (version 0.1.0) functionalities. It was written in R Markdown, using the [knitr](https://cran.r-project.org/package=knitr) package for production. 
See `help(package = "mixMVPLN")` for further details and references provided by `citation("mixMVPLN")`. To download **mixMVPLN**, use the following commands:

``` r
require("devtools")
install_github("anjalisilva/mixMVPLN", build_vignettes = TRUE)
library("mixMVPLN")
```

<br>


## Data Simulation

The function *mvplnDataGenerator* permits to simulate data from a mixture of MVPLN distributions. See *?mvplnDataGenerator* for more information, an example, and references. To simulate a dataset from a mixture of MVPLN with 1000 observations and a dimensionality of 6, with two components, each with a mixing proportion of 0.79 and 0.21, respectively, let us use *mplnDataGenerator*. This also requires the mean and covariance matrix for each component, respectively. 

``` r
 set.seed(1)
true_G <- 2 # number of total G
#' # true_r <- 2 # number of total occasions
#' # true_p <- 3 # number of total responses
#' # true_n <- 100 # number of total units

# Generate means
trueMu1 <- c(6.5, 6, 6, 5, 5, 5) # Mean for component 1  
trueMu2 <- c(2, 2.5, 2, 2, 2, 2) # Mean for component 2
tureMus <- rbind(trueMu1, trueMu2)

# Generate covariances
library(clusterGeneration)
set.seed(1)

# Covariance for component 1  
trueSigma1 <- clusterGeneration::genPositiveDefMat("unifcorrmat", 
                                  dim = dimensionality, 
                                  rangeVar = c(1, 1.5))$Sigma
# Covariance for component 2                                  
trueSigma2 <- clusterGeneration::genPositiveDefMat("unifcorrmat", 
                                  dim = dimensionality, 
                                  rangeVar = c(0.7, 0.7))$Sigma
trueSigma <- rbind(trueSigma1, trueSigma2)

# Generate data 
sampleData <- mplnDataGenerator(nObservations = nObservations,
                                dimensionality = dimensionality,
                                mixingProportions = pig,
                                mu = tureMus,
                                sigma = trueSigma,
                                produceImage = "Yes")

```
<br>

The generated dataset can be checked:

``` r
dim(sampleData$dataset) # 100 x 6 dataset
class(sampleData$dataset) # matrix
typeof(sampleData$dataset) # integer
summary(sampleData$dataset) # summary of data
pairs(sampleData$dataset, col = sampleData$trueMembership + 1,
      main = "Pairs plot of counts") # visualize counts
```

<br>

<div style="text-align:left">
## Clustering
<div style="text-align:left">
Once the count data is available, clustering can be performed using the *mplnParallel* or *mplnNonParallel* function. See *?mplnParallel* or *?mplnNonParallel* for more information, an example, and references. Here, clustering will be performed using the above generated dataset. 

#### Parallel Clustering

Coarse grain parallelization is employed in *mplnParallel*, such that when a range of components/clusters (g = 1,...,G) are considered, each component/cluster size is run on a different processor. This can be performed because each component/cluster size is independent from another. All components/clusters in the range to be tested have been parallelized to run on a seperate core using the *parallel* R package. The number of cores used for clustering is internally determined using *parallel::detectCores() - 1*.

``` r
mplnResults <- MPLNClust::mplnParallel(dataset = sampleData$dataset,
                                       membership = sampleData$trueMembership,
                                       gmin = 1,
                                       gmax = 2,
                                       nChains = 3,
                                       nIterations = 500,
                                       initMethod = "kmeans",
                                       nInitIterations = 2,
                                       normalize = "Yes")
```

The model selected by BIC for this dataset can be viewed as follows.

``` r
mplnResults$BIC_all$BICmodelselected

# Cross tabulation of BIC selected model labels with true lables
table(mplnResults$BIC_all$BICmodelselected_labels, sampleData$truemembership)
```


<br>

